### ISSUE TITLE
many errors are reported when using go get to download the code.the same errors occur when running the example 

### ISSUE THREAD

**Issue by Croton-D** [coussej/gopcua#1]
Many errors are reported when using go get to download the code.The same errors occur when running the example.Such as:
open62541.c:13417: undefined reference to                                                                                           `__imp_shutdown'
open62541.c:13418: undefined reference to                                                                                             `__imp_closesocket'
open62541.c:13431: undefined reference to                                                                                             `__imp_WSACleanup'
go-build140538830\github.com\coussej\gopcua                                                                                            \_obj\open62541.o: In function `socket_close':
open62541.c:13018: undefined reference to                                                                                             `__imp_shutdown'
open62541.c:13019: undefined reference to                                                                                             `__imp_closesocket'
I`m a green hand and confused in how to use package.Can anyone explain it to me ?

**Comment by coussej** [comment]
Hi @Croton-D, I'm not maintaining this as it was an experimental project that was never properly tested and last updated more then 1 year ago. If you want a simple working example, try rolling back to the first commit in this repo, I know that used to work :-). 

Since then I've moved to using OPCUA in a nodeJS environment, as cgo was just 
to much overhead in the dev process.

**Comment by olzhas-ilyubayev** [comment]
Hi @Croton-D 
I don't use "coussej/gopcua", but I also have this problem.
Add `#cgo LDFLAGS: -lws2_32` to imports in gopcua.go or other file, which uses open62541.
Example:

```
/*
#cgo CFLAGS: -std=c99 -I .
#cgo LDFLAGS: -lws2_32
#include <stdlib.h>
#include "gopcua_client.h"

*/
import "C"
```
