### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by lishuaia** [coussej/gopcua#2]
Hello, I found that your program can not run. Can you give me a contact?

**Comment by coussej** [comment]
Hi, sorry this was an experiment from a few years ago and it's really nothing more then that. You shouldn't use this for more than getting some inspiration.

I switched to node-opcua for everything related to UA connectivity...

**Comment by lishuaia** [comment]
> 嗨，对不起这是几年前的一个实验，而且真的不过是那个。你不应该使用它来获得灵感。
> 
> 我切换到node-opcua以获取与UA连接相关的所有内容......

Do you have an example of GoLand writing opcua? Can you send me some information?

**Comment by lishuaia** [comment]
Do you have an example of GoLand writing opcua? Can you send me some information?
